<!DOCTYPE html>
<html lang="en">
<article class='aboutme' id="up">
    <p>Welcome, I'm Emilia. Adventurous and curious; pursuer of great travel experiences.</p>
    <p>I travel to destinations with a story to tell, seeking hidden gems, local specialities, off-the-beaten-track experiences and jaw-dropping natural scenery. I'm drawn to the historical and political context that has shaped the lives of people and framed their collective culture.</p>
    <p>I'm absolutely crazy with the seaside scenery especially in a wild setting,off the beaten tracks.Well,no wonder as I was born and raised at the seaside.</p>
    <p>In doing so, I hope to foster a richer understanding of others and build a better world, one journey at a time.</p>
  <div class='aboutmegallery'>
    <img src="assets/img/selfietravel.jpg" alt=" Travel blog selfie" >
    <img src="assets/img/sis.jpg" alt=" Travel blog pic2" >
    <img src="assets/img/what.jpg" alt=" Travel blog pic">
    <img src="assets/img/london.jpg" alt=" Travel blog pic3" class='aboutmeportrait'>
  </div>
</article>
</html>