<article class="adventures" id="up">
    <h3>A taste of my discoveries</h3>
<div class="gallery">
    <img src="assets/img/prague.jpg" alt="Prague">
    <img src="assets/img/corsicawild.jpg" alt="Corsica beach">
    <img src="assets/img/lisbon.jpg" alt="Lisbon tram" class="portrait">
    <img src="assets/img/paris1.jpg" alt="Paris">
    <img src="assets/img/winterwonder.jpg" alt="Winter tree" class="portrait">
    <img src="assets/img/sky.jpg" alt="Sky">
    <img src="assets/img/VV.jpg" alt="Vama Veche" class="portrait">
    <img src="assets/img/prague1.jpg" alt="Prague1" class="portrait">
</div>
</article>