<article>
<div class="login" >
<div class="form-signin">
   <form action="index.php?page=user" method="post">
      <h1 class="back-door">BACK ACCESS</h1>
         <p>
            <label for="utilisateur" class="visually-hidden" >User</label>
            <input type="text" id="user" name="user" class="form-control"placeholder="user"> 
         <p>
            <label for="password"  class="visually-hidden" >Password</label>
            <input type="password" id="password" name="password"class="form-control" placeholder="password"> 
         </p>
         <button class="back-button">Submit</button>
   </form>
</div>
</div>
</article>