
<div class='banner-city-escapes' id="up">
        <h1>City Escapes</h1>
</div>
<section class='main-wrapper-cityescapes'>
        <div class='galerie-cityescapes'>
                <img src="assets/img/prague.jpg" alt="City Escape">
                <img src="assets/img/Marseille.jpg" alt="Marseille">
                <img src="assets/img/winterwonder.jpg" alt="Prague" class='placesportrait'>
                <img src="assets/img/prague2.jpg" alt="Prague" class='placesportrait'>
                <img src="assets/img/lisbon.jpg" alt="Prague" class='placesportrait'>
                <img src="assets/img/prague1.jpg" alt="Prague" class='placesportrait'>
        </div>
</section>              


