<div class='leave-comment'></div>
    <form action='index.php?page=commentsInfo' method='POST' class='form-height' >
<fieldset id="up">
    <textarea name="text" class="query" id="up"></textarea>
        <div class='form-group has-feedback'>
            <input type='text' class='form-control email' id='email' name='email' placeholder='Email *'>
        </div>
        <div class="toolbar">
            <button type="submit" class="button-comment">Send comment</button>
        </div>
</fieldset>
</form>