<article class='cookie-policy-page'>


<h2> GDPR compliance</h2>
<ul>The GDPR mandates that all websites with visitors from the EU have to:

<li> Obtain clear and unambiguous consent from its users.</li>
<li> Prior to any processing of personal data.</li>
<li> After specifying all types of cookies and other tracking technology present and operating on its pages.</li>
<li> In easy-to-understand ways that enable users to consent and to revoke consent on each specific category of cookies.</li>
<li> To then be able to safely and confidentially document each user consent.</li>
<li> Consent must be renewed annually. However, some national data protection guidelines recommend more frequent renewal, e.g. 6 months. Check your local data protection guidelines for compliance.</li>
</ul>
</article>