

<main class="main-page-container" id="up">

    <section class='travel'>
        <div class='banner'> 
        </div>
            <article>
                <figure>
                <a href="index.php?page=seasidescapes">
                <img src="assets/img/nice.jpg" class='ocean' alt="Seaside">
                    <figcaption>SEASIDE ESCAPES
                    </figcaption></a>
                </figure>
            </article>
            <article>
            <figure>
            <a href="index.php?page=cityescapes">
                <img src="assets/img/prague.jpg" alt="City Escape">
                <figcaption>CITY ESCAPES
                </figcaption>
            </a>
            </figure>
        </article>
        <article>
            <figure>
            <a href="index.php?page=adventures">
                <img src="assets/img/londonbridge.jpg" alt="londonbridge">
                <figcaption>
                ADVENTURES
                </figcaption>
            </a>
            </figure>
        </article>
    </section>
    <section class='experiences'>
        <article>
            <figure>
                <a href="index.php?page=southoffrance"><img src="assets/img/StTropez.jpg" alt="StTropez"></a>
            </figure>
                <a href="index.php?page=southoffrance"><h2>First getaway for 2021 – South of France</h2></a>
                <p>Day 0.5 Was waiting for this day for such a long time. I was so excited to go out again after a very long pause due to the global pandemic situation. Packed my bags late in the morning and realised I have a long way to go to South of France.</p>
                <a href="index.php?page=southoffrance" class='see-more'> View Post </a>
        </article>
        <article class='paris'>
            <figure>
                <a href="index.php?page=southoffrance"><img src="assets/img/paris1.jpg" alt="Paris by night"></a>
            </figure>
                <a href="index.php?page=southoffrance"><h2>Spending summer in Paris 2021</h2></a>
                <p>Was waiting for this day for such a long time. I was so excited to go out again after a very long pause due to the global pandemic situation....</p>
                <a href="index.php?page=southoffrance" class='see-more'> View Post </a>
        </article>
    </section> 
    <section class='activites-marseille' id='activites' >
            <h2>Sneak peek of places I've visited </h2>
            <div class='container-activities'>
                <article class='item'>
                    <a href="#" class='card-image'></a>
                    <img src="assets/img/corsicabeach.jpg" alt="Beautiful Beach">
                    <h3>Beautiful Beach</h3>
                </article>

                <article class='item'>
                    <a href="#" class='card-image'></a>
                    <img src="assets/img/corsicawild.jpg" alt="corsicawild">
                    <h3>Wild Corsica</h3>
                </article>

                <article class='item'>
                    <a href="#" class='card-image'></a>
                    <img src="assets/img/Marseille.jpg" alt="Marseille">
                    <h3><strong>Marseille</strong></h3>
                </article>

                <article class='item'>
                    <a href="#" class='card-image'></a>
                    <img src="assets/img/winterwonder.jpg" alt="Prague">
                    <h3>Prague</h3>
                </article>

                <article class='item'>
                    <a href="#" class='card-image'></a>
                    <img src="assets/img/prague.jpg" alt="City Escape">
                    <h3>City Escape</h3>
                </article>

                <article class='item'>
                    <a href="#" class='card-image'></a>
                    <img src="assets/img/lisbon.jpg" alt="Lisbon" class='placesportrait'>
                    <h3>Lisbon</h3>
                </article>
            </div>
    </section>
        <div class='share-section'></div>
        <div><a id="goBack" class="goInvisible" href="#up"></a></div>

    </main>