<section class='places' id="up">
    <article class='placesdescription'>
        <h2>WHERE DOES YOUR CURIOSITY TAKE YOU?</h2>
            <p>I travel to destinations with a story to tell, seeking hidden gems, local specialities, off-the-beaten-track experiences and jaw-dropping natural scenery.</p>
            <p>My travel writing captures the one thing I always strive to create – incredible travel experiences. From learning about the historical and political context of a destination to finding some really great hikes, each new place has something to discover.</p>
    </article>
    <article class="Italy">
        <h3>Italy</h3>
            <figure>
                <img src="assets/img/nice.jpg" alt="Seaside">
                <img src="assets/img/Paleochora.jpg" alt="Paleochora">
                <img src="assets/img/Paleochora1.jpg" alt="Paleochora1">
                <img src="assets/img/Porquerolle.jpg" alt="Porquerolle" class='placesportrait'>
            </figure>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Neque, explicabo nemo. Maiores odit
                    molestiae, amet saepe, quo mollitia enim delectus vitae tempora ut totam minus fugit officiis
                    aspernatur eum velit?
                </p>
    </article>
    <article class="Corsica">
        <h3>Corsica</h3>
            <figure>
                <img src="assets/img/corsicabeach.jpg" alt="Beautiful Beach"class='placesportrait'>
                <img src="assets/img/corsicawild.jpg" alt="corsicawild"class='placesportrait'>
                <img src="assets/img/wildsea.jpg" alt="sea" class='placesportrait'>
                <img src="assets/img/eveningsun.jpg" alt="eveningsun" class='placesportrait'>
            </figure>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Neque, explicabo nemo. Maiores odit
                    molestiae, amet saepe, quo mollitia enim delectus vitae tempora ut totam minus fugit officiis
                    aspernatur eum velit?
                </p>
    </article>
        <article class="seaside">
        <h3>Seaside Ecapes</h3>
            <figure>
                <img src="assets/img/nice.jpg" alt="Seaside">
                <img src="assets/img/Paleochora.jpg" alt="Paleochora">
                <img src="assets/img/Paleochora1.jpg" alt="Paleochora1">
                <img src="assets/img/VV.jpg" alt="VamaVeche" class='placesportrait'>
            </figure>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Neque, explicabo nemo. Maiores odit
                molestiae, amet saepe, quo mollitia enim delectus vitae tempora ut totam minus fugit officiis
                aspernatur eum velit?
                </p>
    </article>
    <article class="cityescape">
        <h3>City Escapes</h3>
            <figure>
                <img src="assets/img/prague.jpg" alt="City Escape">
                <img src="assets/img/Marseille.jpg" alt="Marseille">
                <img src="assets/img/winterwonder.jpg" alt="Prague" class='placesportrait'>
                <img src="assets/img/prague2.jpg" alt="Prague" class='placesportrait'>
            </figure>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Neque, explicabo nemo. Maiores odit
                    molestiae, amet saepe, quo mollitia enim delectus vitae tempora ut totam minus fugit officiis
                    aspernatur eum velit?
                </p>
    </article>            
</section>