
<article class='register-form'>
    <div class ='banner-register'></div>


        <form action='index.php?page=signUp' method='POST' class='form-size'>

             <div class='form-group has-feedback'>
                <input type='text' class='form-control email' id='email' name='email' placeholder='Your email *'>
    </div>

    <div class='form-group has-feedback'>
              <input type='text'  class='form-control name'id='name' name='name'placeholder='Name'>
    </div>


    <div class='form-group has-feedback'>
         <textarea type='address'  class='form-control address' id='address'name='address'placeholder='Address'></textarea>
    </div>


    <div class='form-group has-feedback'>
         <input type='text'  class='form-control city' id='city' name='city'placeholder='City'>
    </div>


     <div class='form-group has-feedback'>
         <input type='text'  class='form-control country' id='country' name='country'placeholder='Country'>
    </div>



     <div class='form-group has-feedback'>
         <input type='text' class='form-control phone' id='phone' name='phone'placeholder=Phone Number>
     </div>


     <div class='form-submit'>
<button class='register-button'>Subscription</button>
     </div>
</form>

</article>


