
<article class="Greece-seasideescapes" id="up">
      <h1>Greece and Italy</h1>
      <figure>
            <img src="assets/img/Paleochora.jpg" alt="Paleochora">
            <img src="assets/img/positano.jpg" alt=" Travel blog pic4" >
            <img src="assets/img/pompei.jpg" alt=" Travel blog pic5" class='seasideescapeportrait'>
            <img src="assets/img/Porquerolle.jpg" alt="Porquerolle" class='placesportrait'>
      </figure>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Neque, explicabo nemo. Maiores odit
            molestiae, amet saepe, quo mollitia enim delectus vitae tempora ut totam minus fugit officiis
            aspernatur eum velit?
            </p>
</article>

<article class="Corsica-seasideescapes">
      <h1>Corsica</h1>
      <figure>
            <img src="assets/img/corsicabeach.jpg" alt="Beautiful Beach" class='placesportrait'>
            <img src="assets/img/corsicawild.jpg" alt="corsicawild"class='placesportrait'>
            <img src="assets/img/wildsea.jpg" alt="sea" class='placesportrait'>
      </figure>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Neque, explicabo nemo. Maiores oditmolestiae, amet saepe, quo mollitia enim delectus vitae tempora ut totam minus fugit officiis aspernatur eum velit?
            </p>
</article>
