<article class='southoffrance'>
          <div class ='banner-southoffrance'></div>

               <h1>TRAVEL WITH PLEASURE</h1>
                  <h2>First getaway for 2021 – South of France</h2>
                      <p class='date'>Written in Europe on
                           <time datetime='2021-06-05'> 5 June 2021</time>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

           <div class='southoffrancegallery'>
                <img src="assets/img/selfietravel.jpg" alt=" Travel blog selfie">
                <img src="assets/img/london.jpg" alt=" Travel blog pic3" class='aboutmeportrait'>
                <img src="assets/img/positano.jpg" alt=" Travel blog pic4" >
                <img src="assets/img/pompei.jpg" alt=" Travel blog pic5" class='aboutmeportrait'>

           </div>

</article>