<article class='summerparis'>
        <div class ='banner-summerparis'></div>

             <h2>Spending summer in Paris 2021 </h2>
                 <p class='date'>Written in Europe on
                    <time datetime='2021-06-20'> 20 June 2021</time>
                       <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        <div class='summerparisgallery'>
            <img src="assets/img/parisfour.jpg" alt=" Paris">
            <img src="assets/img/paristhree.jpg" alt=" Paris2" class='aboutmeportrait'>
            <img src="assets/img/paristwo.jpg" alt=" Paris3" >
            <img src="assets/img/paris1.jpg" alt=" Paris4" class='aboutmeportrait'>

        </div>

</article>